# Generated by Django 3.1.7 on 2021-03-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_now', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('business_category', models.CharField(choices=[('REST', 'Restaurant'), ('SHOP', 'Retail'), ('GYM', 'Gym or Workout'), ('NONE', 'Other or Unspecified')], default='NONE', max_length=4)),
            ],
        ),
    ]
