# Generated by Django 3.2 on 2021-04-16 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_now', '0005_openinghours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dayofweek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='dayofweek', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TimeField(db_column='timeslot')),
            ],
        ),
        migrations.DeleteModel(
            name='OpeningHours',
        ),
        migrations.AddField(
            model_name='hours',
            name='closetime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hours_closetime', to='open_now.timeslot'),
        ),
        migrations.AddField(
            model_name='hours',
            name='dayofweek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='open_now.dayofweek'),
        ),
        migrations.AddField(
            model_name='hours',
            name='opentime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hours_opentime', to='open_now.timeslot'),
        ),
        migrations.AddField(
            model_name='business',
            name='business_hours',
            field=models.ManyToManyField(blank=True, null=True, to='open_now.Hours'),
        ),
    ]
