# Generated by Django 3.2 on 2021-04-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_now', '0007_auto_20210416_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='weekday_from',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')]),
        ),
    ]
