# Generated by Django 3.2 on 2021-05-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_now', '0009_location_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
