# Generated by Django 3.2 on 2021-05-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_now', '0012_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='email',
            field=models.CharField(default='Guest', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.CharField(default='Guest', max_length=200, null=True),
        ),
    ]
